name: CI

on:
  push:
    branches: 
      - '**' 
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
            envkey_PUSHER_APP_ID: "1743933"
            envkey_PUSHER_KEY: "5c095298c6bebc995925"
            envkey_PUSHER_SECRET: "c7946d260b0d0925e510"
            envkey_PUSHER_CLUSTER: "eu"
      - name: "Run code analysis"
        run: |
          find -name "*.py" -not -path "./env/*" | xargs pylint
      - name: "Run tests"
        run: |
          python manage.py test
      # - name: "Run security checks"
      #   run: |
      #     python manage.py check --deploy --fail-level ERROR
